module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: layouts
      target: layouts
    - source: assets/scss/blocks
      target: assets/scss/blocks
      includeFiles: '**.scss'