module:
  mounts:
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    - source: layouts
      target: layouts
    - source: assets/scss/blocks
      target: assets/scss/blocks
      includeFiles: '**.scss'
    - source: assets/media/sportchemy
      target: assets/media/sportchemy